import { getDatabase, limitToLast, onValue, orderByChild, equalTo, push, query, ref } from 'firebase/database';
import { Filter } from 'bad-words';

/**
 * Comments Service
 */
export const CommentsService = (() => {
    let db, authenticationService;

    /**
     * Initialize the application
     * @param {any} app
     */
    const initialize = async (app, authService) => {
        db = getDatabase(app);
        authenticationService = authService;
    };

    /**
     * Render comments
     * @param {any} comments
     * @param {string} currentUserId
     */
    const renderComments = (comments, currentUserId) => {
        const commentsListElement = document.getElementById('commentsList');
        commentsListElement.innerHTML = '';

        if (comments) {
            Object.values(comments)
                .reverse()
                .forEach((comment) => {
                    const commentUserClass = comment.userId === currentUserId ? 'color-red' : '';

                    const commentHtml = `
                        <blockquote>
                            ${comment.message}
                            <footer>
                                <cite>— <span class='${commentUserClass}'>${comment.userId}</span>, ${new Date(comment.messageTimestamp).toLocaleString()}</cite>
                            </footer>
                        </blockquote>
                    `;

                    commentsListElement.innerHTML += commentHtml;
                });
        } else {
            commentsListElement.innerHTML = `<blockquote>There's nothing around here...</blockquote>`;
        }

        commentsListElement.removeAttribute('aria-busy');
        commentsListElement.removeAttribute('Please wait...');
    };

    /**
     * Load comments
     */
    const loadComments = async () => {
        const commentsRef = ref(db, 'comments/');
        const activeTabUrl = await getCurrentTabURL();
        const commentsQuery = query(
            commentsRef,
            orderByChild('url'),
            equalTo(activeTabUrl),
            limitToLast(20)
        );

        const currentUserId = authenticationService.getOrCreateUserId();

        onValue(commentsQuery, (snapshot) => {
            const comments = snapshot.val();
            renderComments(comments, currentUserId);
        });
    };

    /**
     * Check for profanity
     * @param {string} message
     */
    const checkForProfanity = (message) => {
        const filter = new Filter();

        filter.addWords(
            "abaza",
            "abazan",
            "ağzına sıçayım",
            "ahmak",
            "am",
            "amarım",
            "ambiti",
            "am biti",
            "amcığı",
            "amcığın",
            "amcığını",
            "amcığınızı",
            "amcık",
            "amcık hoşafı",
            "amcıklama",
            "amcıklandı",
            "amcik",
            "amck",
            "amckl",
            "amcklama",
            "amcklaryla",
            "amckta",
            "amcktan",
            "amcuk",
            "amık",
            "amına",
            "amınako",
            "amına koy",
            "amına koyarım",
            "amına koyayım",
            "amınakoyim",
            "amına koyyim",
            "amına s",
            "amına sikem",
            "amına sokam",
            "amın feryadı",
            "amını",
            "amını s",
            "amın oglu",
            "amınoğlu",
            "amın oğlu",
            "amısına",
            "amısını",
            "amina",
            "amina g",
            "amina k",
            "aminako",
            "aminakoyarim",
            "amina koyarim",
            "amina koyayım",
            "amina koyayim",
            "aminakoyim",
            "aminda",
            "amindan",
            "amindayken",
            "amini",
            "aminiyarraaniskiim",
            "aminoglu",
            "amin oglu",
            "amiyum",
            "amk",
            "amkafa",
            "amk çocuğu",
            "amlarnzn",
            "amlı",
            "amm",
            "ammak",
            "ammna",
            "amn",
            "amna",
            "amnda",
            "amndaki",
            "amngtn",
            "amnn",
            "amona",
            "amq",
            "amsız",
            "amsiz",
            "amsz",
            "amteri",
            "amugaa",
            "amuğa",
            "amuna",
            "ana",
            "anaaann",
            "anal",
            "analarn",
            "anam",
            "anamla",
            "anan",
            "anana",
            "anandan",
            "ananı",
            "ananı",
            "ananın",
            "ananın am",
            "ananın amı",
            "ananın dölü",
            "ananınki",
            "ananısikerim",
            "ananı sikerim",
            "ananısikeyim",
            "ananı sikeyim",
            "ananızın",
            "ananızın am",
            "anani",
            "ananin",
            "ananisikerim",
            "anani sikerim",
            "ananisikeyim",
            "anani sikeyim",
            "anann",
            "ananz",
            "anas",
            "anasını",
            "anasının am",
            "anası orospu",
            "anasi",
            "anasinin",
            "anay",
            "anayin",
            "angut",
            "anneni",
            "annenin",
            "annesiz",
            "anuna",
            "aptal",
            "aq",
            "a.q",
            "a.q.",
            "aq.",
            "ass",
            "atkafası",
            "atmık",
            "attırdığım",
            "attrrm",
            "auzlu",
            "avrat",
            "ayklarmalrmsikerim",
            "azdım",
            "azdır",
            "azdırıcı",
            "babaannesi kaşar",
            "babanı",
            "babanın",
            "babani",
            "babası pezevenk",
            "bacağına sıçayım",
            "bacına",
            "bacını",
            "bacının",
            "bacini",
            "bacn",
            "bacndan",
            "bacy",
            "bastard",
            "basur",
            "beyinsiz",
            "bızır",
            "bitch",
            "biting",
            "bok",
            "boka",
            "bokbok",
            "bokça",
            "bokhu",
            "bokkkumu",
            "boklar",
            "boktan",
            "boku",
            "bokubokuna",
            "bokum",
            "bombok",
            "boner",
            "bosalmak",
            "boşalmak",
            "cenabet",
            "cibiliyetsiz",
            "cibilliyetini",
            "cibilliyetsiz",
            "cif",
            "cikar",
            "cim",
            "çük",
            "dalaksız",
            "dallama",
            "daltassak",
            "dalyarak",
            "dalyarrak",
            "dangalak",
            "dassagi",
            "diktim",
            "dildo",
            "dingil",
            "dingilini",
            "dinsiz",
            "dkerim",
            "domal",
            "domalan",
            "domaldı",
            "domaldın",
            "domalık",
            "domalıyor",
            "domalmak",
            "domalmış",
            "domalsın",
            "domalt",
            "domaltarak",
            "domaltıp",
            "domaltır",
            "domaltırım",
            "domaltip",
            "domaltmak",
            "dölü",
            "dönek",
            "düdük",
            "eben",
            "ebeni",
            "ebenin",
            "ebeninki",
            "ebleh",
            "ecdadını",
            "ecdadini",
            "embesil",
            "emi",
            "fahise",
            "fahişe",
            "feriştah",
            "ferre",
            "fuck",
            "fucker",
            "fuckin",
            "fucking",
            "gavad",
            "gavat",
            "geber",
            "geberik",
            "gebermek",
            "gebermiş",
            "gebertir",
            "gerızekalı",
            "gerizekalı",
            "gerizekali",
            "gerzek",
            "giberim",
            "giberler",
            "gibis",
            "gibiş",
            "gibmek",
            "gibtiler",
            "goddamn",
            "godoş",
            "godumun",
            "gotelek",
            "gotlalesi",
            "gotlu",
            "gotten",
            "gotundeki",
            "gotunden",
            "gotune",
            "gotunu",
            "gotveren",
            "goyiim",
            "goyum",
            "goyuyim",
            "goyyim",
            "göt",
            "göt deliği",
            "götelek",
            "göt herif",
            "götlalesi",
            "götlek",
            "götoğlanı",
            "göt oğlanı",
            "götoş",
            "götten",
            "götü",
            "götün",
            "götüne",
            "götünekoyim",
            "götüne koyim",
            "götünü",
            "götveren",
            "göt veren",
            "göt verir",
            "gtelek",
            "gtn",
            "gtnde",
            "gtnden",
            "gtne",
            "gtten",
            "gtveren",
            "hasiktir",
            "hassikome",
            "hassiktir",
            "has siktir",
            "hassittir",
            "haysiyetsiz",
            "hayvan herif",
            "hoşafı",
            "hödük",
            "hsktr",
            "huur",
            "ıbnelık",
            "ibina",
            "ibine",
            "ibinenin",
            "ibne",
            "ibnedir",
            "ibneleri",
            "ibnelik",
            "ibnelri",
            "ibneni",
            "ibnenin",
            "ibnerator",
            "ibnesi",
            "idiot",
            "idiyot",
            "imansz",
            "ipne",
            "iserim",
            "işerim",
            "itoğlu it",
            "kafam girsin",
            "kafasız",
            "kafasiz",
            "kahpe",
            "kahpenin",
            "kahpenin feryadı",
            "kaka",
            "kaltak",
            "kancık",
            "kancik",
            "kappe",
            "karhane",
            "kaşar",
            "kavat",
            "kavatn",
            "kaypak",
            "kayyum",
            "kerane",
            "kerhane",
            "kerhanelerde",
            "kevase",
            "kevaşe",
            "kevvase",
            "koca göt",
            "koduğmun",
            "koduğmunun",
            "kodumun",
            "kodumunun",
            "koduumun",
            "koyarm",
            "koyayım",
            "koyiim",
            "koyiiym",
            "koyim",
            "koyum",
            "koyyim",
            "krar",
            "kukudaym",
            "laciye boyadım",
            "lavuk",
            "liboş",
            "madafaka",
            "mal",
            "malafat",
            "malak",
            "manyak",
            "mcik",
            "meme",
            "memelerini",
            "mezveleli",
            "minaamcık",
            "mincikliyim",
            "mna",
            "monakkoluyum",
            "motherfucker",
            "mudik",
            "oc",
            "ocuu",
            "ocuun",
            "OÇ",
            "oç",
            "o. çocuğu",
            "oğlancı",
            "oğlu it",
            "orosbucocuu",
            "orospu",
            "orospucocugu",
            "orospu cocugu",
            "orospu çoc",
            "orospuçocuğu",
            "orospu çocuğu",
            "orospu çocuğudur",
            "orospu çocukları",
            "orospudur",
            "orospular",
            "orospunun",
            "orospunun evladı",
            "orospuydu",
            "orospuyuz",
            "orostoban",
            "orostopol",
            "orrospu",
            "oruspu",
            "oruspuçocuğu",
            "oruspu çocuğu",
            "osbir",
            "ossurduum",
            "ossurmak",
            "ossuruk",
            "osur",
            "osurduu",
            "osuruk",
            "osururum",
            "otuzbir",
            "öküz",
            "öşex",
            "patlak zar",
            "penis",
            "pezevek",
            "pezeven",
            "pezeveng",
            "pezevengi",
            "pezevengin evladı",
            "pezevenk",
            "pezo",
            "pic",
            "pici",
            "picler",
            "piç",
            "piçin oğlu",
            "piç kurusu",
            "piçler",
            "pipi",
            "pipiş",
            "pisliktir",
            "porno",
            "pussy",
            "puşt",
            "puşttur",
            "rahminde",
            "revizyonist",
            "s1kerim",
            "s1kerm",
            "s1krm",
            "sakso",
            "saksofon",
            "salaak",
            "salak",
            "saxo",
            "sekis",
            "serefsiz",
            "sevgi koyarım",
            "sevişelim",
            "sexs",
            "sıçarım",
            "sıçtığım",
            "sıecem",
            "sicarsin",
            "sie",
            "sik",
            "sikdi",
            "sikdiğim",
            "sike",
            "sikecem",
            "sikem",
            "siken",
            "sikenin",
            "siker",
            "sikerim",
            "sikerler",
            "sikersin",
            "sikertir",
            "sikertmek",
            "sikesen",
            "sikesicenin",
            "sikey",
            "sikeydim",
            "sikeyim",
            "sikeym",
            "siki",
            "sikicem",
            "sikici",
            "sikien",
            "sikienler",
            "sikiiim",
            "sikiiimmm",
            "sikiim",
            "sikiir",
            "sikiirken",
            "sikik",
            "sikil",
            "sikildiini",
            "sikilesice",
            "sikilmi",
            "sikilmie",
            "sikilmis",
            "sikilmiş",
            "sikilsin",
            "sikim",
            "sikimde",
            "sikimden",
            "sikime",
            "sikimi",
            "sikimiin",
            "sikimin",
            "sikimle",
            "sikimsonik",
            "sikimtrak",
            "sikin",
            "sikinde",
            "sikinden",
            "sikine",
            "sikini",
            "sikip",
            "sikis",
            "sikisek",
            "sikisen",
            "sikish",
            "sikismis",
            "sikiş",
            "sikişen",
            "sikişme",
            "sikitiin",
            "sikiyim",
            "sikiym",
            "sikiyorum",
            "sikkim",
            "sikko",
            "sikleri",
            "sikleriii",
            "sikli",
            "sikm",
            "sikmek",
            "sikmem",
            "sikmiler",
            "sikmisligim",
            "siksem",
            "sikseydin",
            "sikseyidin",
            "siksin",
            "siksinbaya",
            "siksinler",
            "siksiz",
            "siksok",
            "siksz",
            "sikt",
            "sikti",
            "siktigimin",
            "siktigiminin",
            "siktiğim",
            "siktiğimin",
            "siktiğiminin",
            "siktii",
            "siktiim",
            "siktiimin",
            "siktiiminin",
            "siktiler",
            "siktim",
            "siktim",
            "siktimin",
            "siktiminin",
            "siktir",
            "siktir et",
            "siktirgit",
            "siktir git",
            "siktirir",
            "siktiririm",
            "siktiriyor",
            "siktir lan",
            "siktirolgit",
            "siktir ol git",
            "sittimin",
            "sittir",
            "skcem",
            "skecem",
            "skem",
            "sker",
            "skerim",
            "skerm",
            "skeyim",
            "skiim",
            "skik",
            "skim",
            "skime",
            "skmek",
            "sksin",
            "sksn",
            "sksz",
            "sktiimin",
            "sktrr",
            "skyim",
            "slaleni",
            "sokam",
            "sokarım",
            "sokarim",
            "sokarm",
            "sokarmkoduumun",
            "sokayım",
            "sokaym",
            "sokiim",
            "soktuğumunun",
            "sokuk",
            "sokum",
            "sokuş",
            "sokuyum",
            "soxum",
            "sulaleni",
            "sülaleni",
            "sülalenizi",
            "sürtük",
            "şerefsiz",
            "şıllık",
            "taaklarn",
            "taaklarna",
            "tarrakimin",
            "tasak",
            "tassak",
            "taşak",
            "taşşak",
            "tipini s.k",
            "tipinizi s.keyim",
            "tiyniyat",
            "toplarm",
            "topsun",
            "totoş",
            "vajina",
            "vajinanı",
            "veled",
            "veledizina",
            "veled i zina",
            "verdiimin",
            "weled",
            "weledizina",
            "whore",
            "xikeyim",
            "yaaraaa",
            "yalama",
            "yalarım",
            "yalarun",
            "yaraaam",
            "yarak",
            "yaraksız",
            "yaraktr",
            "yaram",
            "yaraminbasi",
            "yaramn",
            "yararmorospunun",
            "yarra",
            "yarraaaa",
            "yarraak",
            "yarraam",
            "yarraamı",
            "yarragi",
            "yarragimi",
            "yarragina",
            "yarragindan",
            "yarragm",
            "yarrağ",
            "yarrağım",
            "yarrağımı",
            "yarraimin",
            "yarrak",
            "yarram",
            "yarramin",
            "yarraminbaşı",
            "yarramn",
            "yarran",
            "yarrana",
            "yarrrak",
            "yavak",
            "yavş",
            "yavşak",
            "yavşaktır",
            "yavuşak",
            "yılışık",
            "yilisik",
            "yogurtlayam",
            "yoğurtlayam",
            "yrrak",
            "zıkkımım",
            "zibidi",
            "zigsin",
            "zikeyim",
            "zikiiim",
            "zikiim",
            "zikik",
            "zikim",
            "ziksiiin",
            "ziksiin",
            "zulliyetini",
            "zviyetini",
            "escort",
            "eskort",
            "travesti",
            "gay",
            "kuran",
            "Kuran",
            "incil",
            "tevrat",
            "hz",
            "hzmusa",
            "hz.musa",
            "arefe",
            "ateist",
            "umre",
            "agnostik",
            "caiz",
            "ateizm",
            "deizm",
            "ashab",
            "başörtüsüdür",
            "eshab",
            "fıkıh",
            "ilim",
            "siyer",
            "fitne",
            "hacamat",
            "halife",
            "ictihat",
            "ictihad",
            "ihlas",
            "istiğfar",
            "istigfar",
            "kefaret",
            "tevhid",
            "Allahı",
            "birallah",
            "bir_tanrı",
            "bir tanrı",
            "mahşer",
            "mahser",
            "mubah",
            "mümin",
            "mumin",
            "munafık",
            "münafık",
            "riya",
            "nifak",
            "amel",
            "bektaşi",
            "bektaşilik",
            "mevlana",
            "yunusemre",
            "beytullah",
            "din",
            "budizm",
            "abdest",
            "gusül",
            "gusul",
            "hz.muhammed",
            "hz.idris",
            "hz.adem",
            "hz.yusuf",
            "hz.süleyman",
            "hz.ebubekir",
            "hz.ömer",
            "hz.ali",
            "cennet",
            "cehennem",
            "ahiret",
            "melek",
            "melekler",
            "meleke",
            "günahlar",
            "günahlarla",
            "sevaplarla",
            "hz.",
            "hz",
            "lalegültv",
            "vahiy",
            "meleklere",
            "meleklerle",
            "sevap",
            "rahmet",
            "peygamber",
            "peygamberi",
            "cübbeli",
            "kabir",
            "firavun",
            "tanrı",
            "yehova",
            "rabbi",
            "allah",
            "mikail",
            "cebrail",
            "tengri",
            "israfil",
            "azrail",
            "lut",
            "ayet",
            "hadis",
            "dinicevaplar",
            "sure",
            "bismillah",
            "elhamdulillah",
            "selamunaleyküm",
            "diyanet",
            "din",
            "sa",
            "aleyküm selam",
            "nurcu",
            "nurcular",
            "ismailağa",
            "menzil",
            "tarikat",
            "a.s",
            "fatiha",
            "bakara",
            "al-i imran",
            "maide",
            "en'am",
            "a'raf",
            "enfal",
            "tevbe",
            "yunus suresi",
            "hud suresi",
            "ra'd",
            "nahl",
            "isra",
            "kehf",
            "meryem suresi",
            "enbiya",
            "hac",
            "ümre",
            "tavaf",
            "mü'minun",
            "şuara",
            "neml",
            "kasas",
            "ankebut",
            "lokman",
            "secde",
            "ahzab",
            "sebe",
            "fatır",
            "yasin",
            "saffat",
            "sad",
            "zümer",
            "mü'min",
            "fussilet",
            "şura",
            "zuhruf",
            "duhan",
            "casiye",
            "ahkaf",
            "haram",
            "muhammed",
            "buhari",
            "tirmizi",
            "ebu davud",
            "kaf",
            "zariyat",
            "cihad",
            "necm",
            "kamer",
            "rahman",
            "cin",
            "hadid",
            "haşr",
            "mümtehine",
            "mubarek",
            "hu",
            "teğabun",
            "talak",
            "tahrim",
            "mearic",
            "müzzemmil",
            "müddessir",
            "kıyamet",
            "mürselat",
            "naziat",
            "abese",
            "hasenât",
            "tekvir",
            "intifar",
            "mutaffifin",
            "i̇manla",
            "i̇man",
            "müslüman",
            "inşikak",
            "buruc",
            "a'la",
            "i̇nşallah",
            "inşallah",
            "inşaallah",
            "ğaşiye",
            "cübbe",
            "müslümanlığı",
            "âlim",
            "fecr",
            "beled",
            "hocaefendi",
            "inşirah",
            "kitabu'l-makâlât",
            "papaz",
            "tesbih",
            "şa'bân",
            "tekâmül",
            "kur’ân’a",
            "câmii",
            "beyyine",
            "namâz",
            "duâ",
            "zilzal",
            "îmân",
            "adiyat",
            "tekasür",
            "kureyş",
            "maun",
            "kevser",
            "s.a.v",
            "r.a",
            "nasr",
            "mesed",
            "allah",
            "i̇lâhî",
            "basörtü",
            "Başörtü",
            "Başörtüsü",
            "Başortu",
            "Ortodoks",
            "Başortusu",
            "Başortusü",
            "Başortüsü",
            "sofi",
            "basortu",
            "şeyh",
            "türban",
            "‘aleyhi’s-selâm’a",
            "aleyhi’s-selâm’a",
            "aleyhis selâm",
            "aleyhis selam",
            "radiyallahu anhü",
            "radiyallah anhü",
            "radıyallahuanhu",
            "iftar",
            "sahur",
            "günah",
            "basörtüsü",
            "s.a",
            "kur’an’ın",
            "Hasbünallâhu",
            "es-sünen",
            "ni’me’l-vekîl",
            "dua",
            "pilavlı",
            "Dua",
            "tarikat",
            "şifa-i",
            "şifa-i",
            "cemaat",
            "uhud",
            "zikir",
            "kütüb-i",
            "kütübi",
            "lailaheillah",
            "i̇smâilağa’ya",
            "i̇smâilağa",
            "lailahe",
            "cübbesiz",
            "DUA",
            "ilahi",
            "ezan",
            "ledun",
            "ledunilim",
            "ledunilmi",
            "tesettür",
            "Kilise",
            "kilise",
            "Camii",
            "Cami",
            "cami",
            "camii",
            "chp",
            "mhp",
            "akp",
            "hdp",
            "hukumet",
            "hükümet",
            "iyiparti",
            "dsp",
            "bbp",
            "btp",
            "bdp",
            "ödp",
            "mucadele",
            "cumhur",
            "#oyyok",
            "#herşeygüzelolacak",
            "#herseycokguezelolacak",
            "#darbe",
            "#savas",
            "herşeygüzelolacak",
            "herseyguzelolacak",
            "saldiri",
            "saldırı",
            "i̇mamoğlu’na",
            "ibb",
            "i̇mamoğlu",
            "hdp",
            "siyonist",
            "cumhur",
            "filistin",
            "emniyet",
            "yargila",
            "yargıla",
            "terorist",
            "terorıst",
            "peşmerge",
            "demirel",
            "harekat",
            "iskence",
            "işkence",
            "bahceli",
            "devlet bahçeli",
            "terorizm",
            "terörizm",
            "demokrat",
            "komutan",
            "hurriyet",
            "soykirim",
            "soykırım",
            "askerlik",
            "babacan",
            "muhafazakar",
            "ahmet necdet",
            "fetullah",
            "fetö",
            "FETÖ",
            "saddam huseyin",
            "humeyni",
            "saddam",
            "beşşar esad",
            "beşşar",
            "torpil",
            "deniz baykal",
            "tahliye",
            "milliyetci",
            "hakan sukur",
            "hukumlu",
            "hükümlü",
            "anarşi",
            "militan",
            "rum kesim",
            "partili",
            "savaş",
            "erbakan",
            "saldirgan",
            "karakol",
            "diyanet",
            "ermeni soykirim",
            "ermeni soykırımı",
            "bombala",
            "milliyetcilik",
            "kacakcilik",
            "komunist",
            "suikast",
            "sosyalist",
            "multeci",
            "ambargo",
            "bonbardıman",
            "bombardiman",
            "imparatorluk",
            "ideolojik",
            "ali babacan",
            "ayaklan",
            "susurluk",
            "komiser",
            "barzani",
            "menderes",
            "talabani",
            "padisah",
            "irkcilik",
            "kapitalizm",
            "kan",
            "gerilla",
            "bop",
            "mason",
            "ulliminati",
            "uliminati",
            "hakkari",
            "albayrak",
            "direnisci",
            "diktator",
            "patlayici",
            "astsubay",
            "isgalci",
            "bayraktar",
            "kapitalist",
            "yuzbasi",
            "istiklal",
            "polisiye",
            "ihtilal",
            "provokasyon",
            "militan",
            "marcos",
            "diktatorluk",
            "komunizm",
            "komünizm",
            "statuko",
            "komando",
            "doktrin",
            "vatansever",
            "adalet divanı",
            "pesmerge",
            "terörist",
            "terorist",
            "rektör",
            "saldirganlik",
            "saltanat",
            "kemalist",
            "siyaseten",
            "modernizm",
            "kemalizm",
            "gensoru",
            "gen soru",
            "sosyalizm",
            "sosyalızm",
            "barikat",
            "barıkat",
            "kolektif",
            "romantizm",
            "demirtas",
            "demirtaş",
            "ayasofya",
            "taarruz",
            "emperyalist",
            "dış mihrak",
            "mihrak",
            "ataturkcu",
            "içtihat",
            "içtihad",
            "ictihad",
            "ictihat",
            "atatürk",
            "Atatürk",
            "holigan",
            "silivri",
            "burjuva",
            "korgeneral",
            "anti demokratik",
            "antidemokratik",
            "hukumdar",
            "hükümdar",
            "sizofreni",
            "tumgeneral",
            "seriatci",
            "yasama organ",
            "marksist",
            "totaliter",
            "ugur dundar",
            "adliye sevk",
            "muhakeme",
            "kolelik",
            "vergi memuru",
            "vergı",
            "vergi",
            "fethullah",
            "imamoğlu",
            "erdoğan",
            "bahçeli",
            "bahceli",
            "erdogan",
            "darbe",
            "darbeci",
            "roma imparatorluk",
            "gokturk",
            "osmanlı",
            "tuğra",
            "devlet",
            "nusaybin",
            "proleterya",
            "monarsi",
            "marksizm",
            "bagnazlik",
            "merkeziyetci",
            "homoseksuel",
            "jakoben",
            "federalizm",
            "orgeneral ilker",
            "askeriye",
            "ağlamak",
            "intihar",
            "bıktım",
            "bıkkınım",
            "mantıksız",
            "kuralsız",
            "sorumsuz",
            "saygısız",
            "çaresiz",
            "bıktım",
            "çaresizim",
            "bitiğim",
            "ağlamaktayım",
            "caresizlik",
            "mahveder",
            "mahvettim",
            "öldüm",
            "ölüyorum",
            "üzülmeye",
            "ağlıyor",
            "ağlıyorum",
            "ağlayalım",
            "öldüreceğim",
            "hapis",
            "lanet",
            "sümüklü",
            "ahlaksız",
            "vaiz",
            "saygısız",
            "vah vah",
            "sövsekte",
            "hapis"
        );

        if (filter.isProfane(message)) {
            throw new Error('Please avoid using profanity in your comments.');
        }
    };

    /**
     * Get the current tab URL
     * @param {any} callback
     */
    const getCurrentTabURL = () => {
        return new Promise((resolve, reject) => {
            chrome.tabs.query({ active: true, currentWindow: true }, function (tabs) {
                if (chrome.runtime.lastError) {
                    return reject(chrome.runtime.lastError);
                }
                var activeTab = tabs[0];
                if (activeTab) {
                    resolve(activeTab.url);
                } else {
                    reject("No active tab found");
                }
            });
        });
    };

    /**
     * Submit a comment
     * @param {string} message     
     */
    const submitComment = async (message) => {
        if (!message.trim()) {
            throw new Error('Comment cannot be empty');
        }

        checkForProfanity(message);

        if (message.length < 10) {
            throw new Error('Comment must be at least 10 characters long');
        }

        // Ensure authentication
        if (!authenticationService.isAuthenticated()) {
            await authenticationService.authenticate();
        }

        const commentsRef = ref(db, 'comments/');
        const currentUserId = authenticationService.getOrCreateUserId();
        const messageTimestamp = new Date().toISOString();
        const activeTabUrl = await getCurrentTabURL();

        await push(commentsRef, {
            url: activeTabUrl,
            userId: currentUserId,
            messageTimestamp: messageTimestamp,
            message: message,
        });
    };

    return {
        initialize,
        loadComments,
        submitComment,
    };
})();